### PR TITLE
Convert to python3

### PR DESCRIPTION
**Pull request by patrickocal**
Hi Simon,

Patrick O'Callaghan here. 

We (Cameron Gordon, iciac and I) seem to have successfully converted your lecture 6 code to python3. Apart from print changes and pickle, we swapped the old ipopt wrapper for cyipopt. We are now just trying to check whether it produces consistent results.

Cheers,
Patrick

### CODE REVIEW

**Comment by sischei** [comment]
Dear @path-doc @iciac -- thank you for the updates. Could you please make sure that you do not delete all the lectures, as it happened in the last pull request. Thereafter, I am more than happy to merge.

**Comment by CameronGordon0** [comment]
Hi @sischei, 

Apologies for the mixup! We continued to work on the main branch by mistake. (Still new to Github, so the proper use of forks, branches, pulls, and merging is something we are learning). 

The commit you want is 630a92bf6a86fae5981d62e4f3f15ef80b7a6145. This is already in your history and accompanied by commit message "separate the optimizer classes".

Since we can't make a pull request without making any changes, you can revert to this. But, if you prefer, we can make a minor edit and make a new pull request. 

Best, 

Cameron and Patrick

**Comment by sischei** [comment]
Hi @iciac and @path-doc,

no worries, all fine :)

I would prefer that once all works, there will be simply a second branch or so, I think this would be the easiest for me.

Best wishes
Simon

**Comment by patrickocal** [comment]
All good @sischei, just having a day off :) I do that tomorrow. Will be in
touch soon, Patrick

**Pull request merged**
